# Generated by Django 5.1.1 on 2025-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=5)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
